#!/usr/bin/env bash
LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$LOCAL_DIR/../utils/check_root_permission.sh" || exit 1
source "$LOCAL_DIR/../utils/confirmation_prompt.sh" || exit 1
source "$LOCAL_DIR/../utils/sudo.sh" || exit 1

_download_mcrcon() {
	(
		local RELEASE_FILE="mcrcon-0.7.2-linux-x86-64-static"
		if [ -e /usr/local/bin/mcrcon ] && [ -e /usr/local/share/man/man1/mcrcon.1 ]; then
			echo "mcrcon already installed, skipping ..."
			return 0
		fi

		cd "$LOCAL_DIR" || exit
		curl -OLs https://github.com/Tiiffi/mcrcon/releases/download/v0.7.2/$RELEASE_FILE.zip

		rm -rf mcrcon # remove extracted folder
		unzip $RELEASE_FILE.zip
		rm -f $RELEASE_FILE.zip
		mv $RELEASE_FILE mcrcon

		sudo cp mcrcon/mcrcon /usr/local/bin/mcrcon
		sudo cp mcrcon/mcrcon.1 /usr/local/share/man/man1/mcrcon.1
		rm -rf mcrcon
	)
}

_download_java() {
	if [ -z "$(command -v java)" ]; then
		if confirmation_prompt "No jre instalation found, would you like to install it?"; then
			# https://adoptium.net/installation/linux/
			# TODO: Select jre automatically or let the user choose (maybe even give suggestions)
			# TODO: Detect linux distro and automatically download the package accordingly (or install the binary directly)
			sudo apt install -y wget apt-transport-https gpg
			wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/adoptium.gpg >/dev/null
			echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
			sudo apt update
			sudo apt install temurin-25-jre
		fi
	fi
}

_download_server_jar() {
	local MINECRAFT_VERSION=$1
	local MC_SERVER_LIST_URL
	local MC_SERVER_LIST
	local MC_SERVER_LIST_FORMATTED
	local SERVER_DIR="$LOCAL_DIR/server"
	local SERVER_URL

	if [ -e  "$SERVER_DIR/server.jar" ]; then
		confirmation_prompt "server.jar is already installed would you like to replace it with another version?"
		if [ $? -eq 1 ]; then
			return 0
		fi
	fi

	if [ -z "$MINECRAFT_VERSION" ]; then
		echo "Write minecraft server version you would like to download ex. 1.7.10"
		read -r MINECRAFT_VERSION
	fi

	# minecraft server jars
	# pulled from https://gist.github.com/cliffano/77a982a7503669c3e1acb0a0cf6127e9
	MC_SERVER_LIST_URL="https://gist.githubusercontent.com/cliffano/77a982a7503669c3e1acb0a0cf6127e9/raw/3b92a48d565403a877ebc8209357b59870b9cb6c/minecraft-server-jar-downloads.md"

	MC_SERVER_LIST=$(curl -s $MC_SERVER_LIST_URL | tail -n +3)
	MC_SERVER_LIST_FORMATTED=$(echo "$MC_SERVER_LIST" | cut -d '|' -f 2,3)
	SERVER_URL=$(echo "$MC_SERVER_LIST_FORMATTED" | grep "^\s*$MINECRAFT_VERSION\s" | cut -d '|' -f 2 | tr -d ' \t\n')

	if [ -z "$SERVER_URL" ]; then
		echo "Error: Minecraft version not found, try another version"
		exit 1
	fi

	mkdir -p "$SERVER_DIR"
	rm -f "$SERVER_DIR/server.jar"
	curl -s -o "$SERVER_DIR/server.jar" "$SERVER_URL"
}

main() {
	local MINECRAFT_VERSION=$1
	
	_download_server_jar "$MINECRAFT_VERSION"
	_download_java
	_download_mcrcon
}

if [ "$0" = "${BASH_SOURCE[0]}" ]; then
	main "$@"
fi
