#!/usr/bin/env bash

#TODO: add flag to force shutdown

_is_mcrcon_installed() {
	if [ -e /usr/local/bin/mcrcon ] && [ -e /usr/local/share/man/man1/mcrcon.1 ]; then
		return 0
	else
		return 1
	fi
}

_stop_minecraft_server() {
	local RCON_ENABLED
	local RCON_PASSWORD
	local RCON_PORT

	RCON_ENABLED=$(grep enable-rcon <server/server.properties | cut -d "=" -f 2)
	RCON_PASSWORD=$(grep rcon.password <server/server.properties | cut -d "=" -f 2)
	RCON_PORT=$(grep rcon.port <server/server.properties | cut -d "=" -f 2)

	if ! _is_mcrcon_installed; then
		echo "ERROR: mcrcon is not installed" 1>&2
		exit 1
	fi

	if [ "$RCON_ENABLED" != "true" ]; then
		echo "ERROR: rcon is not enabled" 1>&2
		exit 1
	fi

	mcrcon -P "$RCON_PORT" -p "$RCON_PASSWORD" stop
}

main() {
	_stop_minecraft_server
}

if [ "$0" = "${BASH_SOURCE[0]}" ]; then
	main "$@"
fi
