#!/usr/bin/env bash
PROJECT_ROOT="$(git rev-parse --show-toplevel)/mc-server"

source "$PROJECT_ROOT/../utils/confirmation_prompt.sh" || exit 1
source "$PROJECT_ROOT/utils/server_send_command.bash" || exit 1
source "$PROJECT_ROOT/utils/get_minecraft_server_pid.bash" || exit 1
source "$PROJECT_ROOT/utils/load_dotenv.bash" || exit 1

start_server_in_terminal() {
	local START_SERVER_COMMAND="cd $PROJECT_ROOT/utils && ./start_minecraft_server.bash $*"

	if ! screen -ls | grep -q "$SERVER_TERMINAL_ENV"; then
		screen -AdmS "$SERVER_TERMINAL_ENV" -L -Logfile "$LOG_FILE_ENV" -t tab0 bash
	fi
	
	if [ -n "$(get_minecraft_server_pid)" ] ; then
		echo "Server already running"
		exit 0
	fi

	server_send_command "$START_SERVER_COMMAND"
}

_eula_prompt() {
	local SERVER_DIR="$PROJECT_ROOT/server"
	local EULA="$SERVER_DIR/eula.txt"
	local TIMEOUT=30
	
	SECONDS=0
	until [ -s "$EULA" ] || ((SECONDS >= TIMEOUT)); do
		sleep 1
	done

	if [ ! -s "$EULA" ]; then
		echo "ERROR: Eula.txt could not be found" 1>&2
		exit 1
	fi

	if grep -sq "eula=true" "$EULA"; then
		return 2
	elif grep -sq "eula=false" "$EULA"; then
		echo "Would you like to accept the Minecraft eula?, Y/N"
		echo "You can read it here https://account.mojang.com/documents/minecraft_eula"

		if confirmation_prompt; then
			sed -i "s/eula=false/eula=true/g" "$EULA"
		fi
	fi

}

_add_server_properties() {
	local SERVER_CONFIG="$PROJECT_ROOT/server/server.properties"
	local KEY=$1
	local VALUE=$2
	if grep "$KEY=.*" "$SERVER_CONFIG"; then
		sed -i "/^$KEY=/c\\$KEY=$VALUE" "$SERVER_CONFIG"
	else
		echo "$KEY=$VALUE" >>"$SERVER_CONFIG"
	fi
}

_configure_minecraft_rcon() {
	#https://minecraft.wiki/w/RCON
	local SERVER_CONFIG="$PROJECT_ROOT/server/server.properties"
	local PROMPT="Would you like to enable RCON?"
	if confirmation_prompt "$PROMPT"; then
		_add_server_properties "enable-rcon" "true"

		read -rsp "Please set a password: " RCON_PASSWORD
		_add_server_properties "rcon.password" "$RCON_PASSWORD"

		echo
		read -rp "Select port from 1 to 65535, press Enter to select default (25575): " PORT
		_add_server_properties "rcon.port" "${PORT:-25575}"

		_add_server_properties "broadcast-rcon-to-ops" "false"
	fi
}

main() {
	local MIN_MEMORY="$1"
	local MAX_MEMORY="$2"
	
	start_server_in_terminal "$MIN_MEMORY" "$MAX_MEMORY"

	if _eula_prompt; then
		# Only executes on first run
		_configure_minecraft_rcon
		start_server_in_terminal "$MIN_MEMORY" "$MAX_MEMORY"
	fi
}

if [ "$0" = "${BASH_SOURCE[0]}" ]; then
	main "$@"
fi
