#!/usr/bin/env bash
PROJECT_ROOT="$(git rev-parse --show-toplevel)"
MC_SERVER_ROOT="$PROJECT_ROOT/mc-server"
#TODO: add flag to force shutdown

source "$MC_SERVER_ROOT/utils/get_minecraft_server_pid.bash" || exit 1
source "$MC_SERVER_ROOT/utils/server_send_command.bash" || exit 1
source "$MC_SERVER_ROOT/utils/load_dotenv.bash" || exit 1

_stop_minecraft_server() {
	local MODE=$1
	local TIMEOUT=60

	if [ -z "$(get_minecraft_server_pid)" ]; then 
		echo "WARNING: No minecraft server running"
		exit 0
	fi

	if [ "$MODE" = "f" ]; then # Force
		kill "$(get_minecraft_server_pid)"
		exit 0
	fi

	SECONDS=0
	until ((SECONDS>=TIMEOUT)); do
		local STOP_OUTPUT

		server_send_command stop

		STOP_OUTPUT=$(grep "Stopping the server" "$LOG_FILE_ENV")

		if [[ $STOP_OUTPUT == *"Stopping the server"* ]]; then
			rm -rf "$LOG_FILE_ENV"
			exit 0
		fi

		sleep 1
	done
	
	echo "ERROR: Could not stop minecraft server" 1>&2
	exit 1
}

main() {
	_stop_minecraft_server "$@"
}

if [ "$0" = "${BASH_SOURCE[0]}" ]; then
	main "$@"
fi
